server:
  port: 8099

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  main:
    allow-circular-references: true
  application:
    name: auth-service
  datasource:
      # url: jdbc:mysql://localhost:3306/dbuser
      # username: root
      # password: 12345678q
      # driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://mysql-auth:3306/dbuser
      username: authuser
      password: authpass
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
          minimumIdle: 2
          maximumPoolSize: 5
          cachePrepStmts: true
          prepStmtsCacheSize: 250
          prepStmtsCacheSqlLimit: 2048
          useServerPrepStmts: true
  jpa:
      hibernate:
          ddl-auto: update
      show-sql: true
      properties: 
          hibernate: 
              format-sql: true