server:
  port: 80

jwt:
  secret: ${JWT_SECRET}

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka/
  
